Name:           wayvr
Version:        26.7.1
Release:        1%{?dist}
Summary:        Lightweight OpenXR/OpenVR desktop overlay for Linux

License:        GPL-3.0-only
URL:            https://github.com/wayvr-org/wayvr
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz
Source1:        %{url}/releases/download/v%{version}/vendor.tar.xz

# Upstream currently publishes and tests Linux VR release artifacts primarily on x86_64.
ExclusiveArch:  x86_64

BuildRequires:  alsa-lib-devel
BuildRequires:  cargo
BuildRequires:  clang
BuildRequires:  cmake
BuildRequires:  dbus-devel
BuildRequires:  desktop-file-utils
BuildRequires:  fontconfig-devel
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  glslc
BuildRequires:  libdav1d-devel
BuildRequires:  libinput-devel
BuildRequires:  libshaderc-devel
BuildRequires:  libX11-devel
BuildRequires:  libXext-devel
BuildRequires:  libXrandr-devel
BuildRequires:  libxcb-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  libxkbcommon-x11-devel
BuildRequires:  make
BuildRequires:  mesa-libEGL-devel
BuildRequires:  openvr-devel
BuildRequires:  openxr-devel
BuildRequires:  openssl-devel
BuildRequires:  pipewire-devel
BuildRequires:  pkgconf-pkg-config
BuildRequires:  python3
BuildRequires:  rust
BuildRequires:  systemd-devel
BuildRequires:  vulkan-headers
BuildRequires:  vulkan-loader-devel
BuildRequires:  wayland-devel

Recommends:     xwayland-satellite

%description
WayVR is a lightweight OpenXR/OpenVR overlay that provides access to Wayland
and X11 desktops from Monado, WiVRn, or SteamVR. It also includes wayvrctl for
controlling a running WayVR instance from the command line.

%prep
%autosetup -n wayvr-%{version} -a 1

# The release asset is generated by upstream with `cargo vendor` and includes
# the Cargo source replacement configuration as vendor/vendor-config.toml.
mkdir -p .cargo
install -pm 0644 vendor/vendor-config.toml .cargo/config.toml

%build
export CARGO_HOME="%{_builddir}/cargo-home"
export CARGO_NET_OFFLINE=true
cargo build \
    --release \
    --frozen \
    --offline \
    -p wayvr \
    -p wayvrctl

%install
install -Dm 0755 target/release/wayvr \
    %{buildroot}%{_bindir}/wayvr
install -Dm 0755 target/release/wayvrctl \
    %{buildroot}%{_bindir}/wayvrctl

desktop-file-install \
    --dir=%{buildroot}%{_datadir}/applications \
    wayvr/wayvr.desktop

install -Dm 0644 wayvr/wayvr.png \
    %{buildroot}%{_datadir}/pixmaps/wayvr.png

%check
desktop-file-validate wayvr/wayvr.desktop

%files
%license LICENSE
%doc README.md
%{_bindir}/wayvr
%{_bindir}/wayvrctl
%{_datadir}/applications/wayvr.desktop
%{_datadir}/pixmaps/wayvr.png

%changelog
* Fri Jul 31 2026 nexryai - 26.7.1-1
- Initial COPR package
